services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /opt/mongodb/data:/data/db

  rest_recipes:
    image: craigfoote/rest.recipes:latest
    container_name: rest.recipes
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /opt/rest.recipes/logs:/opt/rest.recipes/logs
    depends_on:
      - mongodb

  ng_recipes:
    image: craigfoote/ng.recipes:latest
    container_name: ng.recipes
    restart: unless-stopped
    ports:
      - 8001:8001
    depends_on:
      - rest_recipes
